# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'parkingApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  pod 'Mapbox-iOS-SDK', '~> 4.9'
  pod 'MapboxNavigation', '~> 0.31.0'
  use_frameworks!

  # Pods for parkingApp

  target 'parkingAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
